[package]
name = "example"
version = "0.1.0"
authors = ["André Terranchie <andre.terranchie@seb.se>"]
edition = "2018"

[dependencies]
server = { path = "../server" }
tokio = "0.1.15"
futures = "0.1.25"